ARG VERSION

# Start from the container that we created in stage 1
From subsurface/mxe-build-container:$VERSION

# this time the settings include QtWebKit - since everything else was built
# during the first stage, QtWebKit will be the only thing that gets built
ADD settings-stage2.mk /win/mxe/settings.mk
