# Build the image using the --build-arg option, e.g.:
# docker build -t boret/myimage:0.1 --build-arg=mxe_sha=123ABC456 .
#

# Start from Ubuntu
From ubuntu:18.04
ARG mxe_sha=master
ENV _ver=${mxe_sha}

# update and set up the packages we need for this cross build
RUN apt-get update
