# Build the image using the --build-arg option, e.g.:
# docker build -t boret/myimage:0.1 --build-arg=mxe_sha=123ABC456 .
#

From subsurface/mxe-build-container:0.1.stage1
ARG mxe_sha=master
ENV _ver=${mxe_sha}
RUN mkdir -p /win
ADD settings-stage1.mk /win/settings.mk
RUN cd /win ; git clone git://github.com/mxe/mxe ; \
    cd mxe ; \
    git checkout ${_ver} ;
RUN mv /win/settings.mk /win/mxe
RUN cd /win/mxe ; \
    make -j 6 2>&1 | tee build.log ;
RUN cd /win/mxe ; \
    make MXE_TARGETS=i686-w64-mingw32.static glib -j 6 2>&1 | tee -a build.log ;
