name: Docker Image CI

on:
  push:
    branches:
    - master
#    paths:
#    - scripts/docker/mxe-build-container/*


jobs:
  mxe-build-container-stage1:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    env:
      VERSION: 0.1

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -f ./scripts/docker/mxe-build-container/Dockerfile-stage1 ./scripts/docker/mxe-build-container/ --tag docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mxe-build-container-stage1:${VERSION}

    - name: Push the Docker image
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY/\/*/} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mxe-build-container-stage1:${VERSION}

  mxe-build-container-stage2:
    runs-on: ubuntu-latest
    needs:   mxe-build-container-stage1
    timeout-minutes: 720
    env:
      VERSION: 0.1

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -f ./scripts/docker/mxe-build-container/Dockerfile-stage2 ./scripts/docker/mxe-build-container/ --tag docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mxe-build-container:${VERSION}

    - name: Push the Docker image
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY/\/*/} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mxe-build-container:${VERSION}

