name: Docker Image CI

on:
  push:
    branches:
    - master
#    paths:
#    - scripts/docker/mxe-build-container/*


jobs:
  mxe-build-container-stage1:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    env:
      # IMPORTANT: use the second digit to test new versions, each new official build should be n.0 with the first one being 1.0
      #            as you test changes toward a new release, call those 1.1, 1.2, 1.3, etc
      #            VERSION is just that version presented as a string constant
      #
      VERSION: ${{ '0.3' }}

    steps:
    - uses: actions/checkout@v1

      # Because, reasons, we can't really do anything in YAML, so do this crazy shell callout thingy in order to assemble
      # sane variables to use later in this job
      # this abomination below assembles the docker image NAME and appends ".stage1" to the VERSION
    - name: set env
      run: |
        v=${{ env.VERSION }}
        s=".stage1"
        echo "::set-env name=NAME::subsurface/mxe-build-container:${v}${s}"

    - name: Build and Publish stage 1 Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:       ${{ env.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'Dockerfile-stage1'
        workdir:    './scripts/docker/mxe-build-container/'

    - name: Trigger stage 2 to run
      run: |
        curl -XPOST -H 'authorization: token ${{ secrets.ACCESS_TOKEN }}' \
                    -H "Accept: application/vnd.github.everest-preview+json" \
                    -H "Content-Type: application/json" \
                    https://api.github.com/repos/dirkhh/docker/dispatches \
                    --data '{"event_type": "${{ env.VERSION }}" }'
