name: Docker Image CI

on:
  push:
    branches:
    - master
#    paths:
#    - scripts/docker/mxe-build-container/*


jobs:
  mxe-build-container-stage1:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    env:
      VERSION: 0.1

    steps:
    - uses: actions/checkout@v1

    - name: Build and Publish stage 1 Docker image to Dockerhub
      uses: saubermacherag/gpr-docker-publish@master
      with:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_TAG: 0.1.stage1
        DOCKERFILE_PATH: './scripts/docker/mxe-build-container/Dockerfile-stage1'
        BUILD_CONTEXT: './scripts/docker/mxe-build-container/'
        DOCKERHUB_REPOSITORY: 'subsurface/mxe-build-container'

    - name: Build and Publish stage 2 Docker image to Dockerhub
      uses: saubermacherag/gpr-docker-publish@master
      with:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_TAG: 0.1.stage2
        DOCKERFILE_PATH: './scripts/docker/mxe-build-container/Dockerfile-stage2'
        BUILD_CONTEXT: './scripts/docker/mxe-build-container/'
        DOCKERHUB_REPOSITORY: 'subsurface/mxe-build-container'

    - name: Build and Publish final Docker image to Dockerhub
      uses: saubermacherag/gpr-docker-publish@master
      with:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_TAG: 0.1
        DOCKERFILE_PATH: './scripts/docker/mxe-build-container/Dockerfile-stage3'
        BUILD_CONTEXT: './scripts/docker/mxe-build-container/'
        DOCKERHUB_REPOSITORY: 'subsurface/mxe-build-container'

